---
title: "iBlastoid analysis"
output: html_document
---

---
title: "02_Ethan_iBlastoids_SC_day6"
author: "jibsch"
date: "2020-07-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(Seurat)
library(org.Hs.eg.db)
```

## Load the Data
```{r}
seurat_d6 = CreateSeuratObject(Read10X("../data/RL2157_2020_06_24_20_2175_32F38F1_scRNAseq/RL2157_all/outs/filtered_feature_bc_matrix/"), min.cells = 0, min.features = 0, project = "D6_iBlastoids")

seurat_d6[["percent.mt"]] <- PercentageFeatureSet(seurat_d6, pattern = "^MT-")
```

## Pre Process
```{r}


donors = read_tsv("~/projects/Ethan_iBlastoids/data/donor_ids.tsv")

summary(row.names(seurat_d6@meta.data) == donors$cell)

ggplot(donors, aes(prob_doublet, ..density..)) + geom_density()

seurat_d6$donor = donors$donor_id
seurat_d6 = seurat_d6[,donors$prob_doublet< 0.5 & donors$donor_id!="unassigned"]

ggplot(seurat_d6@meta.data, aes(nFeature_RNA, ..density..)) +
  geom_density(aes(colour=orig.ident)) + 
  geom_vline(xintercept = 1300, linetype="dashed") +
  theme_classic()

ggplot(seurat_d6@meta.data, aes(percent.mt, ..density..)) +
  geom_density(aes(colour=orig.ident)) + 
  geom_vline(xintercept = 15, linetype="dashed") +
  theme_classic()

seurat_d6 = seurat_d6[,seurat_d6$percent.mt < 15 &
                                     seurat_d6$nFeature_RNA > 1300 ]
```

```{r}
genes_in_cells_1 = rowSums(as.matrix(seurat_d6@assays$RNA@counts) >0)
summary(genes_in_cells_1 > 50)
row.names(seurat_d6)[grepl("SENDAI", row.names(seurat_d6)) & genes_in_cells_1 > 50]

seurat_d6 = seurat_d6[genes_in_cells_1 > 50, ]
seurat_d6 = SCTransform(seurat_d6)

```

## Process Data
```{r}
seurat_d6 = RunPCA(seurat_d6, verbose = FALSE)
ElbowPlot(seurat_d6)
seurat_d6 = RunUMAP(seurat_d6, dims = 1:20)
DimPlot(seurat_d6, reduction = "umap")

seurat_d6 = RunTSNE(seurat_d6, dims = 1:20)
DimPlot(seurat_d6, reduction = "tsne", group.by = "cell_type", label = TRUE)
```

### list 1
```{r}
list_epi = c("KLF17", "NANOG", "IFI16", "PRDM14", "TFCP2L1", "POU5F1")
FeaturePlot(seurat_d6, features = list_epi)
```
### List 2
```{r}
list_pe = c("GATA6", "SOX17", "GATA4", "FOXA2")
FeaturePlot(seurat_d6, features = list_pe)
```
### List 3
```{r}
list_te = c("NR2F2", "TFAP2C", "GATA2", "GATA3", "CDX2", "KRT7", "TBX3")
FeaturePlot(seurat_d6, features = list_te)
```


### List 4
```{r}
list_fib = c("ANPEP", "SNAI2", "TWIST1")
FeaturePlot(seurat_d6, features = list_fib)
```

### List 5
```{r}
FeaturePlot(seurat_d6, features = 
              c("HLA-G", "MMP2", "CGB1", "SDC1", "ERVW-1", "IFNAR1"))
```

### List 6
```{r}
FeaturePlot(seurat_d6, features = 
              c("T", "FGF4", "FGF8", "CER1", "MIXL1", "HLX1"))
```




## Clustering

```{r}
seurat_d6 = FindNeighbors(seurat_d6, dims = 1:20)

x = FindClusters(seurat_d6, resolution = seq(0.2,1.4,0.2))

library(clustree)

clustree(x)

DimPlot(x, group.by = "SCT_snn_res.0.2", label=TRUE)

seurat_d6 = FindClusters(seurat_d6, resolution = 0.7)
```
```{r}
DimPlot(seurat_d6, label = TRUE)
```
```{r}
VlnPlot(seurat_d6, features = list_epi, ncol = 2)

VlnPlot(seurat_d6, features = list_te)

VlnPlot(seurat_d6, features = list_pe, ncol = 2)

VlnPlot(seurat_d6, features = list_fib,)
```



```{r}
seurat_d6$cell_type = recode(seurat_d6$seurat_clusters, 
                            "3" = "EPI",
                            "1" = "PE", 
                            "2" = "TE",
                            "5" = "FIB")
```

```{r}
ggplot(seurat_d6@meta.data, aes(seurat_clusters, percent.mt)) +
  geom_boxplot() + theme_classic()
```








## Marker Genes
```{r}
markers_d6 = FindAllMarkers(seurat_d6, only.pos = TRUE)
```


```{r}
library(openxlsx)
wb = createWorkbook()
lm = markers_d6[markers_d6$p_val_adj<=0.05, ]

for(l in levels(factor(lm$cluster))) {
  addWorksheet(wb, sheetName = l)
  writeDataTable(wb, sheet = l, lm[lm$cluster == l,])
}
saveWorkbook(wb, file = "../output/cluster_markers.xlsx", overwrite = TRUE)
rm(lm)
```









## Cluster Scores
```{r}
nature_sig = read.table("~/projects/Ethan_iBlastoids/data/suppTable03.tab", 
           header=TRUE, sep="\t", as.is = TRUE)
nature_sig.list = split(nature_sig$geneName, f=factor(nature_sig$module))

petro_sig = read.table("~/projects/Ethan_iBlastoids/data/suppTable12.tab", 
           header=TRUE, sep="\t", as.is = TRUE)

petro_sig.list = split(petro_sig$geneName, f=factor(petro_sig$type))

```

```{r}
seurat_d6 = AddModuleScore(seurat_d6, 
                           features = petro_sig.list, name = names(petro_sig.list))

seurat_d6 = AddModuleScore(seurat_d6, 
                           features = nature_sig.list[c("fibroblast", "nonReprog1")], name = names(nature_sig.list[c("fibroblast", "nonReprog1")]))
```

```{r}
seurat_d6 = SetIdent(seurat_d6, value = "cell_type")
seurat_d6.cluster_exp = AverageExpression(seurat_d6)
```


```{r}
mural_polar = read_csv("../data/signatures/petropolous_mural_polar.csv", )
mural_polar$signature = ifelse(mural_polar$log2.fc > 0, "polar", "mural")
mural_polar = mural_polar[mural_polar$E6andE7.p<0.05,]

mural_polar.list = split(mural_polar$gene, factor(mural_polar$signature))

seurat_d6 = AddModuleScore(seurat_d6, features = mural_polar.list, name = names(mural_polar.list))

names(seurat_d6@meta.data)[37:38] = c("mural","polar")

FeaturePlot(seurat_d6, features = c("mural","polar")) &
  scale_color_gradientn(colours = rev(brewer.pal(n = 10, name =
 "RdYlBu")))

ggplot(as_tibble(seurat_d6@meta.data) %>% filter(cell_type2=="TE"),
       aes(mural1, polar2)) + geom_point()
as_tibble(seurat_d6@meta.data) %>% filter(cell_type2=="TE") -> x
cor(x$mural1, x$polar2)

summary(mural_polar.list$mural %in% mural_polar.list$polar)
```

```{r}
TE = seurat_d6[,seurat_d6$cell_type2 == "TE"]
TE = SCTransform(TE)
TE = RunPCA(TE, verbose = FALSE)
TE = RunUMAP(TE, dims=1:10)
FeaturePlot(TE, features = c("mural_E6_100_0.01","polar_E6_100_0.01")) &
  scale_color_gradientn(colours = rev(brewer.pal(n = 10, name =
 "RdYlBu")))



Embeddings(TE, reduction = "umap") %>% 
  cbind(scale(TE@meta.data[,c("mural_E6_100_0.01","polar_E6_100_0.01")])) %>% as_tibble() %>%
  gather(key = "subtype", value = "value",-UMAP_1, -UMAP_2) %>% 
  ggplot(., aes(UMAP_1, UMAP_2, weight=value)) +
    geom_hex(bins=15) +
    facet_wrap(~subtype) +
    scale_fill_gradientn(colours = rev(brewer.pal(n = 10, name = "RdYlBu"))) +
  theme_classic()

Embeddings(TE, reduction = "umap") %>% 
  cbind(TE@meta.data[,c("mural1","polar2")]) %>%
  ggplot(., aes(UMAP_1, UMAP_2, weight=mural1-polar2)) +
    geom_hex() 

FeaturePlot(TE, features = c("PLCE1", "NRP1"))
```

```{r}
Embeddings(TE, reduction = "umap") %>% 
  cbind(scale(TE@meta.data[,c("mural_E6_100_0.01","polar_E6_100_0.01")])) %>% as_tibble() %>%
  gather(key = "subtype", value = "value",-UMAP_1, -UMAP_2) %>%
  mutate(st = recode(subtype,  "mural_E6_100_0.01" = "mural",
                     "polar_E6_100_0.01" = "polar")) %>%
  ggplot(aes(UMAP_1,..count.., weight=value)) +
  geom_histogram(bins=50, aes(fill=subtype),  alpha=0.5) +
  facet_wrap(~st, scales = "free_y", ncol = 1) +
  scale_fill_manual(values = mcolor) +
  labs(x="UMAP1", y="binned subtype score") +
  theme_classic() +
  theme(legend.position = "none")
  
```


```{r}
TE = FindNeighbors(TE, dims=1:10)
TE=FindClusters(TE)
DimPlot(TE)
cmark = FindAllMarkers(TE, only.pos = TRUE)
cmark %>% filter(p_val_adj<0.05) %>%
  left_join(mural_polar) -> x

x %>% filter(abs(log2.fc) >= 1) -> y

x %>% filter(cZ.p <= 0.01) -> z
table(x$signature, x$cluster)
table(y$signature, y$cluster)
table(z$signature, z$cluster)
```

```{r}
TE@meta.data %>% 
  mutate(mural_E6_100_0.01=scale(mural_E6_100_0.01), 
         polar_E6_100_0.01=scale(polar_E6_100_0.01)) %>%
  group_by(seurat_clusters) %>%
  summarise(t.adj = t.test(mural_E6_100_0.01, polar_E6_100_0.01)$p.value*7)

```

```{r}
mcolor = c("mural_E6_100_0.01" = "darkred", 
           "polar_E6_100_0.01" = "darkblue")
ggplot(TE@meta.data %>% 
         select(seurat_clusters, mural_E6_100_0.01, polar_E6_100_0.01) %>%
         mutate(mural_E6_100_0.01 = scale(mural_E6_100_0.01),
                polar_E6_100_0.01 = scale(polar_E6_100_0.01)) %>%
         mutate(subtype = recode(seurat_clusters,
                                 "0" = "polar", "1"="polar", "6"="polar",
                                 "2"="mural", "4"="mural",
                                 "3"="mix","5"="mix")) %>%
         gather("signature", "value", - seurat_clusters, -subtype),
       aes(seurat_clusters, value, fill=signature)) +
  #geom_point(aes(group=signature), alpha=0.5, size=0.01, position = "jitter") +
  #geom_jitter(aes(colour=signature), size=0.01)+
 # geom_point(position = position_jitterdodge(dodge.width=0.9), size=0.01) +
  geom_boxplot(aes(fill=signature), position="dodge2", 
               notch = TRUE, outlier.shape = NA, alpha=0.5) +
  facet_grid(.~subtype, scale="free_x", space = "free") +
  scale_fill_manual(values = mcolor, labels=c("mural", "polar"))+
  theme_classic() + 
  theme(legend.position = "bottom") +
  labs(x="cluster id", y="Z signature score")-> p; p

ggplot(TE@meta.data %>% 
         select(seurat_clusters, mural_E6_100_0.01, polar_E6_100_0.01) %>%
         mutate(mural_E6_100_0.01 = scale(mural_E6_100_0.01),
                polar_E6_100_0.01 = scale(polar_E6_100_0.01)) %>%
         mutate(subtype = recode(seurat_clusters,
                                 "0" = "polar", "1"="polar", "6"="polar",
                                 "2"="mural", "4"="mural",
                                 "3"="mix","5"="mix")) %>%
         gather("signature", "value", - seurat_clusters, -subtype),
       aes(seurat_clusters, value)) +
  geom_violin(aes(fill=signature), position="dodge", alpha=0.5) +
  scale_fill_manual(values = mcolor, labels=c("mural", "polar"))+
  facet_wrap(~subtype, scale="free_x") +
  theme_classic() +
  theme(legend.position = "bottom") +
  labs(x="cluster id", y="Z signature score")
```



```{r}
mural_polar2 = read_csv("../data/signatures/petropolous_mural_polar.csv", )
mural_polar2$signature = ifelse(mural_polar2$log2.fc > 0, "polar", "mural")
mural_polar2 = mural_polar2[mural_polar2$cZ.p<0.05,]

mural_polar.list2 = split(mural_polar2$gene, factor(mural_polar2$signature))

seurat_d6 = AddModuleScore(seurat_d6, features = mural_polar.list2, name = names(mural_polar.list2))

FeaturePlot(seurat_d6, features = c("mural1","polar2")) &
  scale_color_gradientn(colours = rev(brewer.pal(n = 10, name =
 "RdYlBu")))
```

```{r}
FeaturePlot(TE, features = c("mural","polar","mural1","polar2"), ncol=2) &
  scale_color_gradientn(colours = rev(brewer.pal(n = 10, name =
 "RdYlBu")))
```


```{r}
mural_polar3 = read_csv("../data/signatures/petropolous_mural_polar.csv", )
mural_polar3$signature = ifelse(mural_polar3$log2.fc > 0, "polar", "mural")
mural_polar3 = mural_polar3[mural_polar3$cZ.p<=0.01,]

mural_polar3 %>% group_by(signature) %>% top_n(.,n=100, wt=abs(log2.fc)) -> mural_polar3

mural_polar.list3 = split(mural_polar3$gene, factor(mural_polar3$signature))

seurat_d6 = AddModuleScore(seurat_d6, features = mural_polar.list3, name = names(mural_polar.list3))

names(seurat_d6@meta.data)[47:48] = c("mural_E6_100_0.01", "polar_E6_100_0.01" )

FeaturePlot(seurat_d6, features = c("mural_E6_100_0.01", "polar_E6_100_0.01")) &
  scale_color_gradientn(colours = rev(brewer.pal(n = 10, name =
 "RdYlBu")))

ggplot(as_tibble(TE@meta.data),
       aes(scale(mural_E6_100_0.01), scale(polar_E6_100_0.01))) + geom_point() +
  facet_wrap(~seurat_clusters) + 
  geom_abline(intercept = 0, slope = 1, colour="red") +
  theme_classic()
```

## Cell Cycle
```{r}
library(scran)

hs.pairs <- readRDS(system.file("exdata", "human_cycle_markers.rds", package="scran"))

sse = Seurat::as.SingleCellExperiment(seurat_d6)



g = mapIds(org.Hs.eg.db, row.names(sse), keytype = "SYMBOL", column = "ENSEMBL")

row.names(sse) = g

assigned <- cyclone(sse, pairs=hs.pairs)
rm(sse)

head(assigned$scores)
table(assigned$phases, seurat_d6$cell_type)

seurat_d6$phase = assigned$phases

```



## Cluster Correlation
```{r}
as.matrix(seurat_d6@assays$SCT@data) %>% as_tibble(rownames = "gene") %>%
  gather("cell", "value", -gene) %>%
  left_join(data.frame(cell = row.names(seurat_d6@meta.data), c = seurat_d6@active.ident)) %>%
  group_by(c, gene) %>% summarise(value = mean(value)) %>%
  spread(key = "c", value = "value") %>% as.data.frame() -> means
  

row.names(means) = means$gene
cor = cor(means[,-1])
pheatmap::pheatmap(cor)
```



